import type { Metadata } from "next";
import { Providers } from "@/redux/provider";
import { Header } from "@/components";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="fa">
      <body
        suppressHydrationWarning={true}
        className="font-iranSans bg-gray-100"
      >
        <Providers>
          <header>
            <Header />
          </header>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
